name: Custom Workflow

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
    inputs:
      inp1:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
        - octocat
      inp2:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
        - octocat
      inp3:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
        - octocat

jobs:
  example_job1:
    name: Example Job 1
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - run: echo "${{ github.event.inputs.inp1 }}"

  example_job2:
    name: Example Job 2
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: echo "${{ github.event.inputs.inp2 }}"

  example_job3:
    name: Example Job 3
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: echo "${{ github.event.inputs.inp3 }}"
