name: Environment Variables
on:
  workflow_dispatch:

env:
    ENV_V_1: "ge1_v"
    ENV_V_2: "ge2_v"
    ENV_V_3: "ge3_v"
    
jobs:
  job_with_env:
    name: Job with Env
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: |
        echo "ENV_V_1: $ENV_V_1"
        echo "ENV_V_2: $ENV_V_2"
        echo "ENV_V_3: $ENV_V_3"
      env:
        ENV_V_3: "je3_v"
  job_without_env:
    name: Job without Env
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: |
        echo "ENV_V_1: $ENV_V_1"
        echo "ENV_V_2: $ENV_V_2"
        echo "ENV_V_3: $ENV_V_3"
