name: Manual Trigger with Input
on:
  workflow_dispatch:
    inputs:
      inp:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
        - octocat
jobs:
  example_job:
    name: Example Job 
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: echo "${{ github.event.inputs.inp }}"
