name: Composite Action Workflow

on: 
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use my composite action
        uses: ./.github/actions/my-composite-action
        with:
          node-version: '18'

      - name: Display result
        run: |
          echo "Script Result: ${{ steps.run-script.outputs.result }}"