name: Composite Action Workflow

on: 
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use my composite action
        uses: ./.github/actions/my-composite-action
        with:
          node-version: '18'
      - name: Display result
        run: |
          echo "Script Result: ${{ steps.run-script.outputs.result }}"

      - name: Install MyCLI
        uses: ./.github/actions/my-cli-action
        with:
          version: '1.2.3'          
      - name: Verify CLI Installation
        run: |
          echo "Checking MyCLI version..."
          mycli --version
          